import type { ControlKey } from '../gpu/pipeline'

export interface SliderDef {
  key: ControlKey
  label: string
  min: number
  max: number
  step: number
  unit: string
}

export interface Group {
  name: string
  sliders: SliderDef[]
  // Audio group: rendered inside the Audio section next to the enable button,
  // not in the generic list.
  audio?: boolean
  // A/B mix groups: surfaced next to the Input row when source B is on,
  // rather than buried in the generic group list at the bottom.
  ab?: boolean
}

export const GROUPS: Group[] = [
  {
    name: 'Signal (source A)',
    sliders: [
      {
        key: 'invert',
        label: 'invert (polarity swap)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'deint',
        label: 'deinterlace (capture combing)',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
      },
    ],
  },
  {
    name: 'Cable / Wiring',
    sliders: [
      {
        key: 'polarityFlip',
        label: 'hard polarity (flips sync)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'termination',
        label: 'termination (-1 daisy, +1 open)',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'chromaPinOnly',
        label: 'chroma-pin only (no luma/sync)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'connectorGlitch',
        label: 'loose connector',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Camera Feedback',
    sliders: [
      { key: 'fbMix', label: 'mix', min: 0, max: 1, step: 0.01, unit: '' },
      {
        key: 'fbZoom',
        label: 'zoom',
        min: 0.7,
        max: 1.6,
        step: 0.005,
        unit: 'x',
      },
      {
        key: 'fbRotateDeg',
        label: 'rotate',
        min: -30,
        max: 30,
        step: 0.1,
        unit: 'deg',
      },
      {
        key: 'fbShiftX',
        label: 'shift x',
        min: -0.3,
        max: 0.3,
        step: 0.001,
        unit: '',
      },
      {
        key: 'fbShiftY',
        label: 'shift y',
        min: -0.3,
        max: 0.3,
        step: 0.001,
        unit: '',
      },
      {
        key: 'fbGain',
        label: 'gain',
        min: 0.5,
        max: 1.5,
        step: 0.005,
        unit: 'x',
      },
      {
        key: 'fbFocus',
        label: 'defocus',
        min: 0,
        max: 3,
        step: 0.05,
        unit: 'px',
      },
      {
        key: 'fbVign',
        label: 'vignette',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'fbBlack',
        label: 'black cut',
        min: 0,
        max: 0.2,
        step: 0.005,
        unit: '',
      },
      {
        key: 'fbKnee',
        label: 'cam s-curve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'crtCutoff',
        label: 'beam cutoff',
        min: 0,
        max: 0.6,
        step: 0.01,
        unit: '',
      },
      {
        key: 'crtGamma',
        label: 'beam gamma',
        min: 1,
        max: 3,
        step: 0.05,
        unit: '',
      },
      {
        key: 'crtSat',
        label: 'beam saturation',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
      },
      {
        key: 'crtBloom',
        label: 'screen bloom',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
      },
      {
        key: 'crtHalation',
        label: 'halation (warm halo)',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
      },
      {
        key: 'crtGlow',
        label: 'phosphor glow',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Mixer Loop (composite)',
    sliders: [
      {
        key: 'cfbMix',
        label: 'loop mix',
        min: 0,
        max: 0.95,
        step: 0.01,
        unit: '',
      },
      {
        key: 'cfbGain',
        label: 'loop gain',
        min: -1.2,
        max: 1.2,
        step: 0.01,
        unit: 'x',
      },
      {
        key: 'cfbDelayUs',
        label: 'loop delay',
        min: 0,
        max: 8,
        step: 0.001,
        unit: 'us',
      },
      {
        key: 'cfbLines',
        label: 'v offset',
        min: -20,
        max: 20,
        step: 1,
        unit: 'lines',
      },
      {
        key: 'cfbKey',
        label: 'luma key',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'cfbKeyLevel',
        label: 'key level',
        min: 0,
        max: 100,
        step: 0.5,
        unit: 'IRE',
      },
      {
        key: 'cfbKeySoft',
        label: 'key soft',
        min: 1,
        max: 30,
        step: 0.5,
        unit: 'IRE',
      },
      {
        key: 'cfbHold',
        label: 'strobe hold',
        min: 0,
        max: 60,
        step: 1,
        unit: 'frames',
      },
      {
        key: 'cfbTrail',
        label: 'trails',
        min: 0,
        max: 0.98,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Dirty Mix (source B)',
    ab: true,
    sliders: [
      {
        key: 'bGain',
        label: 'B gain',
        min: 0,
        max: 1.2,
        step: 0.01,
        unit: 'x',
      },
      { key: 'bRing', label: 'ring mod', min: 0, max: 1, step: 0.01, unit: '' },
      {
        key: 'bLineHz',
        label: 'line offset',
        min: -8,
        max: 8,
        step: 0.01,
        unit: 'Hz',
      },
      {
        key: 'bDetuneHz',
        label: 'sc detune',
        min: -400,
        max: 400,
        step: 0.5,
        unit: 'Hz',
      },
      {
        key: 'bRollLps',
        label: 'frame roll',
        min: -3,
        max: 3,
        step: 0.01,
        unit: 'l/f',
      },
      {
        key: 'bHueDeg',
        label: 'B hue',
        min: -180,
        max: 180,
        step: 1,
        unit: 'deg',
      },
      {
        key: 'bVidGain',
        label: 'B video gain',
        min: 0,
        max: 2,
        step: 0.01,
        unit: 'x',
      },
      { key: 'bInv', label: 'B invert', min: 0, max: 1, step: 0.01, unit: '' },
    ],
  },
  {
    name: 'Wipe (A/B)',
    ab: true,
    sliders: [
      {
        key: 'wipeMode',
        label: 'pattern (0 off, h, v, box, diamond)',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
      },
      {
        key: 'wipePos',
        label: 'position',
        min: 0,
        max: 1,
        step: 0.001,
        unit: '',
      },
      {
        key: 'wipeSoft',
        label: 'softness',
        min: 0,
        max: 0.5,
        step: 0.005,
        unit: '',
      },
      {
        key: 'wipeRate',
        label: 'sweep',
        min: 0,
        max: 2,
        step: 0.01,
        unit: 'Hz',
      },
    ],
  },
  {
    name: 'PiP inset (source B)',
    ab: true,
    sliders: [
      {
        key: 'pipMix',
        label: 'inset key',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      { key: 'pipX', label: 'center x', min: 0, max: 1, step: 0.005, unit: '' },
      { key: 'pipY', label: 'center y', min: 0, max: 1, step: 0.005, unit: '' },
      { key: 'pipW', label: 'width', min: 0.1, max: 1, step: 0.005, unit: '' },
      { key: 'pipH', label: 'height', min: 0.1, max: 1, step: 0.005, unit: '' },
      {
        key: 'pipBorder',
        label: 'border',
        min: 0,
        max: 0.03,
        step: 0.001,
        unit: '',
      },
      {
        key: 'pipSoft',
        label: 'edge soft',
        min: 0,
        max: 0.05,
        step: 0.001,
        unit: '',
      },
      {
        key: 'pipKey',
        label: 'luma key (- inverts)',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'pipKeyLevel',
        label: 'key level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'pipKeySoft',
        label: 'key soft',
        min: 0.01,
        max: 0.4,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Tape / Channel',
    sliders: [
      {
        key: 'lumaMHz',
        label: 'luma bandwidth',
        min: 1.2,
        max: 6,
        step: 0.05,
        unit: 'MHz',
      },
      {
        key: 'lumaPeak',
        label: 'peaking',
        min: 0,
        max: 3,
        step: 0.05,
        unit: '',
      },
      {
        key: 'noiseIre',
        label: 'noise',
        min: 0,
        max: 40,
        step: 0.1,
        unit: 'IRE',
      },
      {
        key: 'ghostDelayUs',
        label: 'ghost delay',
        min: 0,
        max: 12,
        step: 0.05,
        unit: 'us',
      },
      {
        key: 'ghostGain',
        label: 'ghost gain',
        min: -0.6,
        max: 0.6,
        step: 0.01,
        unit: '',
      },
      { key: 'humAmp', label: 'hum', min: 0, max: 30, step: 0.1, unit: 'IRE' },
      {
        key: 'soundIre',
        label: 'sound carrier',
        min: 0,
        max: 10,
        step: 0.1,
        unit: 'IRE',
      },
      {
        key: 'dropoutRate',
        label: 'dropouts',
        min: 0,
        max: 60,
        step: 1,
        unit: '/frame',
      },
      {
        key: 'dropoutLenUs',
        label: 'dropout len',
        min: 1,
        max: 25,
        step: 0.5,
        unit: 'us',
      },
      {
        key: 'dubGens',
        label: 'dub generations',
        min: 1,
        max: 4,
        step: 1,
        unit: 'x',
      },
    ],
  },
  {
    name: 'VHS Chroma',
    sliders: [
      {
        key: 'colorUnderMix',
        label: 'color-under',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'underJitterDeg',
        label: 'phase jitter',
        min: 0,
        max: 25,
        step: 0.1,
        unit: 'deg/line',
      },
    ],
  },
  {
    name: 'VHS Tracking',
    sliders: [
      {
        key: 'trackAmt',
        label: 'tracking error',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'trackPos',
        label: 'band position',
        min: 0,
        max: 1,
        step: 0.005,
        unit: '',
      },
    ],
  },
  {
    name: 'Timebase',
    sliders: [
      {
        key: 'tbJitterNs',
        label: 'flutter',
        min: 0,
        max: 800,
        step: 5,
        unit: 'ns',
      },
      { key: 'tbWowNs', label: 'wow', min: 0, max: 2000, step: 10, unit: 'ns' },
      {
        key: 'headSwitchShiftUs',
        label: 'head switch',
        min: -3,
        max: 3,
        step: 0.05,
        unit: 'us',
      },
      {
        key: 'headSwitchNoise',
        label: 'switch noise',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Sync',
    sliders: [
      {
        key: 'hHold',
        label: 'horizontal hold',
        min: 0.02,
        max: 0.8,
        step: 0.01,
        unit: '',
      },
      {
        key: 'vHold',
        label: 'vertical hold (lock authority)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'vFreqHz',
        label: 'vertical osc (60 = locked)',
        min: 50,
        max: 70,
        step: 0.05,
        unit: 'Hz',
      },
      {
        key: 'syncBendUs',
        label: 'retrace flag (top hook)',
        min: 0,
        max: 12,
        step: 0.05,
        unit: 'us',
      },
      {
        key: 'hDetuneHz',
        label: 'horizontal osc detune',
        min: -500,
        max: 500,
        step: 1,
        unit: 'Hz',
      },
    ],
  },
  {
    name: 'Audio',
    audio: true,
    sliders: [
      {
        key: 'audioRoll',
        label: 'bass → vertical hold (lurch)',
        min: 0,
        max: 8,
        step: 0.05,
        unit: 'Hz',
      },
      {
        key: 'audioTear',
        label: 'level → horizontal hold (tear)',
        min: -400,
        max: 400,
        step: 1,
        unit: 'Hz',
      },
      {
        key: 'audioSagUs',
        label: 'bass → HV sag (smack, needs ring)',
        min: 0,
        max: 40,
        step: 0.5,
        unit: 'us',
      },
      {
        key: 'audioBendUs',
        label: 'waveform into deflection (literal)',
        min: -20,
        max: 20,
        step: 0.1,
        unit: 'us',
      },
      {
        key: 'audioLoad',
        label: 'audio into HV tank (needs sag)',
        min: 0,
        max: 3,
        step: 0.01,
        unit: '',
      },
      {
        key: 'audioGain',
        label: 'input trim',
        min: 0,
        max: 4,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Deflection',
    sliders: [
      {
        key: 'bendUs',
        label: 'bend amount',
        min: -30,
        max: 30,
        step: 0.1,
        unit: 'us',
      },
      {
        key: 'bendShape',
        label: 'shape (0 flag, 1 skew, 2 bow, 3 ripple)',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
      },
      {
        key: 'bendPeriod',
        label: 'decay / ripple period',
        min: 4,
        max: 480,
        step: 1,
        unit: 'lines',
      },
      {
        key: 'hvSagUs',
        label: 'HV sag (beam pulls scan)',
        min: -25,
        max: 25,
        step: 0.1,
        unit: 'us',
      },
      {
        key: 'hvRing',
        label: 'supply ring (0 droop, 1 chaos)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
    ],
  },
  {
    name: 'Decoder',
    sliders: [
      {
        key: 'combMode',
        label: 'Y/C comb (0 trap, 1-2 comb)',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
      },
      {
        key: 'svideoBleed',
        label: 'S-video bleed (Y/C miswire)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'demodMHz',
        label: 'chroma bandwidth',
        min: 0.15,
        max: 1.5,
        step: 0.01,
        unit: 'MHz',
      },
      {
        key: 'chromaTail',
        label: 'chroma trail (causal bleed)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'chromaCoarse',
        label: 'chroma upsample error',
        min: 1,
        max: 8,
        step: 1,
        unit: 'px',
      },
      {
        key: 'chromaGain',
        label: 'chroma gain',
        min: 0,
        max: 3,
        step: 0.01,
        unit: 'x',
      },
      {
        key: 'burstLock',
        label: 'burst lock',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'killThresh',
        label: 'color killer',
        min: 0,
        max: 15,
        step: 0.1,
        unit: 'IRE',
      },
      { key: 'agc', label: 'agc', min: 0, max: 1, step: 0.01, unit: '' },
      {
        key: 'encChromaMHz',
        label: 'encoder chroma bw',
        min: 0.3,
        max: 2,
        step: 0.01,
        unit: 'MHz',
      },
    ],
  },
  {
    name: 'Display',
    sliders: [
      {
        key: 'scanBeam',
        label: 'beam profile',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'crtSharp',
        label: 'reconstruction (bilinear→cubic)',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'phosphor',
        label: 'phosphor persistence',
        min: 0,
        max: 0.98,
        step: 0.01,
        unit: '',
      },
      {
        key: 'maskAmt',
        label: 'aperture grille',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
      },
      {
        key: 'maskPitch',
        label: 'grille pitch',
        min: 1.5,
        max: 12,
        step: 0.5,
        unit: 'px',
      },
    ],
  },
]
